In [1]:
import numpy as np

In [3]:
arr =np.array([1,2,3,45])
print(arr)

[ 1  2  3 45]


In [4]:
import time

In [9]:

size=10_000_000

python_list=list(range(size))
start=time.time()

list_squared=[x**2 for x in python_list]
end=time.time()

print("Python list time ", end-start, "seconds")

np_array=np.array(python_list)
start=time.time()

array_squared=np_array **2
end=time.time()

print("Numpy array time ", end-start, "seconds")

Python list time  0.20090198516845703 seconds
Numpy array time  0.006531953811645508 seconds


In [10]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr3, arr3.shape)


[[1 2 3]
 [4 5 6]] (2, 3)


In [11]:
arr1 = np.zeros((3, 4))
print(arr1, arr1.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)


In [15]:
arr2=np.array([1,2,3,4,5,6,7,])
print(arr2.shape)

(7,)


In [18]:
reshaped=arr2.reshape((1,7))
print(reshaped)

[[1 2 3 4 5 6 7]]


In [20]:
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
